name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Ensure Android/iOS platforms exist
        run: |
          flutter create .

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build release APK
        run: |
          flutter build apk --release --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
